03-sfc 01 task
js-tasks-ru/vue-20210810_valeoprime pull request #4
Opened 2021-08-24 13:33 UTC by ValeoPrime

2021-08-24 13:34 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-24 14:39 UTC, ShGKme requested changes
Изображение по умолчанию не сработало...

2021-08-24 14:39 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +    },
`url(--default-cover)` не сработает в CSS. `--default-cover` - CSS переменная, её значение надо получать функцией `var`. А `url` уже в значении переменной.

2021-08-25 07:46 UTC, ValeoPrime commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +    },
Кажись вкурил, сейчас перезалью решение

2021-08-25 07:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-25 07:49 UTC, closed without merging

2021-08-25 07:49 UTC, ValeoPrime commented
fix